import type { Metadata } from 'next'
import { Direction } from 'radix-ui'
import { Theme } from '@radix-ui/themes'
import { Snackbar } from '@Roots'
import localFont from 'next/font/local'
import '@styles/index.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const iranYekan = localFont({
  display: 'block',
  fallback: [],
  style: 'normal',
  adjustFontFallback: false,

  src: [
    {
      path: '../assets/fonts/IRANYekanXFaNum-Thin.woff2',
      weight: '100'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-UltraLight.woff2',
      weight: '200'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-Light.woff2',
      weight: '300'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-Regular.woff2',
      weight: '400'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-Medium.woff2',
      weight: '500'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-DemiBold.woff2',
      weight: '600'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-Bold.woff2',
      weight: '700'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-ExtraBold.woff2',
      weight: '800'
    },
    {
      path: '../assets/fonts/IRANYekanXFaNum-Black.woff2',
      weight: '900'
    }
  ]
})

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" dir="rtl">
      <Direction.Provider dir="rtl">
        <body className={iranYekan.className}>
          <Theme>
            <Snackbar />
            {children}
          </Theme>
        </body>
      </Direction.Provider>
    </html>
  )
}
