import type { Metadata } from 'next'
import { Direction } from 'radix-ui'
import { Theme } from '@radix-ui/themes'
import { Snackbar } from '@Roots'
import '@styles/index.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" dir="rtl">
      <Direction.Provider dir="rtl">
        <body>
          <Theme>
            <Snackbar />
            {children}
          </Theme>
        </body>
      </Direction.Provider>
    </html>
  )
}
